name: Build Vue
on:
  push:
    branches:
      - master
jobs:
  build_vue:
    runs-on: ubuntu-latest
    name: Build Vue
    steps:
      - uses: actions/checkout@v4
      - name: build
        run: |
          npm ci
          npm run build
          mv dist/ docs/
          git config --global user.email "${{ inputs.gitemail }}"
          git config --global user.name "${{ inputs.gitname }}"
          git init
          git add -A
          git commit -m '${{ inputs.gitmsg }}'
          git push -f https://${{ inputs.username }}:${{ inputs.token }}@github.com/${{ inputs.username }}/${{ inputs.reponame }}.git master:gh-pages
